server:
  port: 8085

spring:
  application:
    name: notification-service

  mail:
    host: ${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:2525}
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-v2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.wellwipes.common.event"

wellwipes:
  notification:
    from-email: "no-reply@well-wipes.local"
    from-name: "Well-Wipes"
    admin-email: "admin@well-wipes.local"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.wellwipes.notificationservice: DEBUG
