events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    sendfile on;
    keepalive_timeout 65;
    gzip on;

    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;
        server_name _;

        location / {
            set $fe http://frontend:80;
            proxy_pass $fe;
            proxy_set_header Host $host;
        }

        location /api/ {
            set $gw http://api-gateway:8080;
            proxy_pass $gw;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
        }

        location /oauth2/ {
            set $auth http://auth-service:8081;
            proxy_pass $auth;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
        }

        location /login/oauth2/ {
            set $auth http://auth-service:8081;
            proxy_pass $auth;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
        }
    }
}
